# Generated by Django 6.0.4 on 2026-04-28 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_attendance_attendancerecord'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance', 'worker_name')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('site', 'name')},
        ),
    ]
