# Generated by Django 6.0.4 on 2026-07-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_workerphotoreport_workerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='national_id_image',
            field=models.ImageField(default=1, upload_to='attendance/id_cards/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
