# Generated by Django 6.0.4 on 2026-08-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_attendancerecord_national_id_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerphotoreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='workerphotoreport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='workerphotoreport',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_photo_reports', to='operations.shift'),
            preserve_default=False,
        ),
    ]
