# Generated by Django 6.0.4 on 2026-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_workerphotoreport_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerphotoreport',
            name='notes',
        ),
        migrations.AddField(
            model_name='workerphoto',
            name='image_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('report', 'Report')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
