# Generated by Django 6.0.4 on 2026-08-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_remove_workerphotoreport_notes_and_more'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlastlocation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_locations', to='sites.site'),
        ),
    ]
