# Generated by Django 6.0.4 on 2026-08-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_userlastlocation_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlastlocation',
            name='site',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='site',
        ),
    ]
