# Generated by Django 6.0.4 on 2026-08-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_remove_userlastlocation_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='national_id_image',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('with_permission', 'غائب باذن'), ('without_permission', 'غائب بدون اذن')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='worker_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/worker_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب')], max_length=10),
        ),
    ]
