# Generated by Django 6.0.4 on 2026-08-23 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_remove_attendancerecord_national_id_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('with_permission', 'غائب باذن'), ('without_permission', 'غائب بدون اذن'), ('sick', 'إجازة مرضية'), ('annual', 'إجازة سنوية'), ('other', 'إجازة أخرى')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workerphotoreport',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
