# Generated by Django 6.0.4 on 2026-07-26 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('operations', '0005_workerphotoreport_workerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='operations.shift'),
            preserve_default=False,
        ),
    ]
