# Generated by Django 6.0.4 on 2026-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_area_manager_site_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='break_workers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='reserve_workers_count',
            field=models.IntegerField(default=0),
        ),
    ]
