# Generated by Django 6.0.4 on 2026-06-01 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0005_workerphotoreport_workerphoto'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaklyCleaningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakly_cleaning_reports', to='operations.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakly_cleaning_reports', to='sites.site')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakly_cleaning_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeaklyCleaningReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='weakly_reports/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('report', 'Report'), ('before', 'Before'), ('after', 'After')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.weaklycleaningreport')),
            ],
        ),
    ]
