# Generated by Django 6.0.4 on 2026-06-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_workerphotoreport_workerphoto'),
        ('reports', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaklycleaningreportfile',
            name='report',
        ),
        migrations.CreateModel(
            name='WeeklyCleaningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_cleaning_reports', to='operations.shift')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_cleaning_reports', to='sites.site')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_cleaning_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCleaningReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='weekly_reports/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('report', 'Report'), ('before', 'Before'), ('after', 'After')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.weeklycleaningreport')),
            ],
        ),
        migrations.DeleteModel(
            name='WeaklyCleaningReport',
        ),
        migrations.DeleteModel(
            name='WeaklyCleaningReportFile',
        ),
    ]
