# Generated by Django 6.0.4 on 2026-06-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_workerphotoreport_workerphoto'),
        ('reports', '0003_incidentreport_incidentimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandoverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_status', models.CharField(choices=[('clean', 'نظيف'), ('follow_up', 'يحتاج متابعه'), ('incomplete', 'غير مكتمل')], max_length=20)),
                ('completed_work', models.TextField()),
                ('remaining_work', models.TextField()),
                ('workers_count', models.PositiveIntegerField()),
                ('ongoing_issues', models.TextField(blank=True, null=True)),
                ('handover_method', models.CharField(choices=[('direct', 'تسليم مباشر'), ('without_receiving', 'بدون تسليم مباشر')], max_length=30)),
                ('is_received', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_handovers', to=settings.AUTH_USER_MODEL)),
                ('next_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_handovers', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handover_reports', to='operations.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shift_handover/%Y/%m/%d/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.shifthandoverreport')),
            ],
        ),
    ]
