# Generated by Django 6.0.4 on 2026-07-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_shifthandoverreport_shifthandoverimage'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifthandoverreport',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='handover_reports', to='sites.site'),
            preserve_default=False,
        ),
    ]
