# Generated by Django 6.0.4 on 2026-08-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_incidentreport_site'),
        ('reports', '0006_alter_shifthandoverreport_next_supervisor'),
    ]

    operations = [
    ]
