<<<<<<< ours
# Generated by Django 6.0.4 on 2026-08-11 12:03
=======
# Generated by Django 6.0.4 on 2026-08-16 20:38
>>>>>>> theirs

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
