# Generated by Django 6.0.4 on 2026-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('area_manager', 'Area Manager'), ('site_manager', 'Site Manager'), ('supervisor', 'Supervisor')], default='supervisor', max_length=20),
        ),
    ]
