# Generated by Django 6.0.4 on 2026-07-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('operations', '0005_workerphotoreport_workerphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreceipt',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='request_date',
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audits', to='operations.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='shift',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_receipts', to='operations.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_requests', to='operations.shift'),
            preserve_default=False,
        ),
    ]
